/// Integration test for the config template generated by `arb config --ensure-only`.
///
/// We run the `arb` binary with `XDG_CONFIG_HOME` pointed at a temporary directory so
/// that `minimal_user_config_template()` writes a fresh `arb.lua` without touching the
/// real user config.  Then we read the generated file and verify expected content markers.
#[cfg(target_os = "macos")]
mod tests {
    use std::fs;
    use std::process::Command;

    #[test]
    fn should_produce_valid_lua_config_template() {
        let temp = tempfile::tempdir().unwrap();
        let config_home = temp.path().join("xdg_config");
        fs::create_dir_all(&config_home).unwrap();

        let arb_bin = env!("CARGO_BIN_EXE_arb");

        let output = Command::new(arb_bin)
            .arg("config")
            .arg("--ensure-only")
            .env("XDG_CONFIG_HOME", &config_home)
            .output()
            .expect("failed to run arb config --ensure-only");

        assert!(
            output.status.success(),
            "arb config --ensure-only failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        let config_file = config_home.join("arb").join("arb.lua");
        assert!(
            config_file.exists(),
            "expected config file at {} does not exist",
            config_file.display()
        );

        let content = fs::read_to_string(&config_file).expect("read generated config file");

        // The template must be valid UTF-8 (read_to_string would have failed otherwise)
        // and non-empty.
        assert!(!content.is_empty(), "config template must be non-empty");

        assert!(
            content.contains("local wezterm = require"),
            "template must contain `local wezterm = require`"
        );
        assert!(
            content.contains("return config"),
            "template must contain `return config`"
        );
        assert!(
            content.contains("resolve_bundled_config"),
            "template must contain `resolve_bundled_config`"
        );
    }
}
